// <auto-generated />
using System;
using ICD10.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ICD10.API.Migrations
{
    [DbContext(typeof(ICD10DbContext))]
    [Migration("20180826152824_AddICD9Codes")]
    partial class AddICD9Codes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ICD10.API.Models.ICD10Category", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ICD10.API.Models.ICD10Code", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AbbreviatedDescription");

                    b.Property<string>("DiagnosisCode");

                    b.Property<string>("FullDescription");

                    b.Property<Guid>("ICD10CategoryId");

                    b.HasKey("ID");

                    b.HasIndex("ICD10CategoryId");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("ICD10.API.Models.ICD9Code", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("LongDescription");

                    b.Property<string>("ShortDescription");

                    b.Property<int>("Version");

                    b.HasKey("ID");

                    b.ToTable("ICD9Codes");
                });

            modelBuilder.Entity("ICD10.API.Models.ICD10Code", b =>
                {
                    b.HasOne("ICD10.API.Models.ICD10Category", "Category")
                        .WithMany("ICD10Codes")
                        .HasForeignKey("ICD10CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
